"""Constants for AWS backup scripts."""

import re


S3_BACKUP_BUCKET_ENV = "A_SHARE_DB_S3_BACKUP_BUCKET"
DEFAULT_S3_BACKUP_PREFIX = "quant/a_share_db/data_backups"
DEFAULT_KEEP_BACKUPS = 10
DEFAULT_S3_STORAGE_CLASS = "GLACIER"
TIMESTAMP_FORMAT = "%Y%m%dT%H%M%SZ"
TIMESTAMP_PATTERN = r"^\d{8}T\d{6}Z$"
TIMESTAMP_RE = re.compile(TIMESTAMP_PATTERN)
S3_DELETE_BATCH_SIZE = 1000

SUPPORTED_S3_STORAGE_CLASSES = {
    "STANDARD",
    "STANDARD_IA",
    "ONEZONE_IA",
    "INTELLIGENT_TIERING",
    "GLACIER_IR",
    "GLACIER",
    "DEEP_ARCHIVE",
}
