"""Constants for financial statement and fundamental tables.

Each provider table is described by an ordered mapping from Tushare field to
local column. Provider field lists and local column lists are derived from the
same mapping so the two can never drift apart.

Statement tables are partitioned by report period (data/financial/{table}/{period}.csv)
because Tushare bulk interfaces (income_vip etc.) return one period for the whole
market per request, which is far cheaper than one request per stock.
"""

# Header fields shared by the three statements.
_STATEMENT_HEADER_MAP = {
    "ts_code": "code",
    "ann_date": "announce_date",
    "f_ann_date": "actual_announce_date",
    "end_date": "report_period",
    "report_type": "statement_type",
    "comp_type": "company_type",
    "end_type": "period_type",
}

# Provider report_type codes. 1 (合并报表) is the default for quant use.
TUSHARE_STATEMENT_TYPE_MAP = {
    "1": "consolidated",
    "2": "single_quarter",
    "3": "cumulative_adjusted",
    "4": "consolidated_prior",
    "5": "prior_consolidated_adjusted",
    "6": "parent",
    "7": "parent_single_quarter",
    "8": "parent_prior",
    "9": "parent_prior_adjusted",
    "10": "consolidated_single_quarter_adjusted",
    "11": "parent_single_quarter_adjusted",
    "12": "consolidated_prior_period",
}
DEFAULT_STATEMENT_REPORT_TYPES = ["1"]

# Company type: 1 general, 2 bank, 3 insurer, 4 broker.
TUSHARE_COMPANY_TYPE_MAP = {
    "1": "general",
    "2": "bank",
    "3": "insurance",
    "4": "securities",
}

# Financial statements exist from the early 1990s; periods are quarterly.
DEFAULT_FINANCIAL_START_DATE = "19900101"
FINANCIAL_PAGE_SIZE = 5000

# Statement rows are unique by code + period + statement type + actual announce date.
STATEMENT_KEY_COLUMNS = ["code", "report_period", "statement_type", "actual_announce_date"]

# ---------------------------------------------------------------------------
# Income statement (income / income_vip)
# ---------------------------------------------------------------------------
TUSHARE_INCOME_FIELD_MAP = {
    **_STATEMENT_HEADER_MAP,
    "basic_eps": "basic_eps",
    "diluted_eps": "diluted_eps",
    "total_revenue": "total_revenue",
    "revenue": "revenue",
    "int_income": "interest_income",
    "prem_earned": "premiums_earned",
    "comm_income": "commission_income",
    "n_commis_income": "net_commission_income",
    "n_oth_income": "net_other_income",
    "n_oth_b_income": "net_other_business_income",
    "prem_income": "premium_income",
    "out_prem": "ceded_premiums",
    "une_prem_reser": "unearned_premium_reserve_change",
    "reins_income": "reinsurance_income",
    "n_sec_tb_income": "net_securities_brokerage_income",
    "n_sec_uw_income": "net_securities_underwriting_income",
    "n_asset_mg_income": "net_asset_management_income",
    "oth_b_income": "other_business_income",
    "fv_value_chg_gain": "fair_value_change_gain",
    "invest_income": "investment_income",
    "ass_invest_income": "associate_investment_income",
    "forex_gain": "foreign_exchange_gain",
    "total_cogs": "total_operating_costs",
    "oper_cost": "operating_cost",
    "int_exp": "interest_expense",
    "comm_exp": "commission_expense",
    "biz_tax_surchg": "business_tax_and_surcharges",
    "sell_exp": "selling_expense",
    "admin_exp": "administrative_expense",
    "fin_exp": "financial_expense",
    "assets_impair_loss": "asset_impairment_loss",
    "prem_refund": "premium_refund",
    "compens_payout": "claims_payout",
    "reser_insur_liab": "insurance_liability_reserve_change",
    "div_payt": "policyholder_dividend_payout",
    "reins_exp": "reinsurance_expense",
    "oper_exp": "operating_expense",
    "compens_payout_refu": "claims_payout_recovery",
    "insur_reser_refu": "insurance_reserve_recovery",
    "reins_cost_refund": "reinsurance_cost_recovery",
    "other_bus_cost": "other_business_cost",
    "operate_profit": "operating_profit",
    "non_oper_income": "non_operating_income",
    "non_oper_exp": "non_operating_expense",
    "nca_disploss": "non_current_asset_disposal_loss",
    "total_profit": "total_profit",
    "income_tax": "income_tax",
    "n_income": "net_profit",
    "n_income_attr_p": "net_profit_attributable_to_parent",
    "minority_gain": "minority_interest_profit",
    "oth_compr_income": "other_comprehensive_income",
    "t_compr_income": "total_comprehensive_income",
    "compr_inc_attr_p": "comprehensive_income_attributable_to_parent",
    "compr_inc_attr_m_s": "comprehensive_income_attributable_to_minority",
    "ebit": "ebit",
    "ebitda": "ebitda",
    "insurance_exp": "insurance_expense",
    "undist_profit": "undistributed_profit_beginning",
    "distable_profit": "distributable_profit",
    "rd_exp": "research_and_development_expense",
    "fin_exp_int_exp": "financial_interest_expense",
    "fin_exp_int_inc": "financial_interest_income",
    "transfer_surplus_rese": "transfer_from_surplus_reserve",
    "transfer_housing_imprest": "transfer_from_housing_fund",
    "transfer_oth": "transfer_from_other",
    "adj_lossgain": "prior_period_adjustment",
    "withdra_legal_surplus": "statutory_surplus_reserve_appropriation",
    "withdra_legal_pubfund": "statutory_public_welfare_fund_appropriation",
    "withdra_biz_devfund": "business_development_fund_appropriation",
    "withdra_rese_fund": "reserve_fund_appropriation",
    "withdra_oth_ersu": "other_surplus_reserve_appropriation",
    "workers_welfare": "employee_welfare",
    "distr_profit_shrhder": "profit_distributable_to_shareholders",
    "prfshare_payable_dvd": "preferred_dividend_payable",
    "comshare_payable_dvd": "common_dividend_payable",
    "capit_comstock_div": "common_dividend_capitalized",
    "net_after_nr_lp_correct": "net_profit_after_non_recurring_items",
    "credit_impa_loss": "credit_impairment_loss",
    "net_expo_hedging_benefits": "net_hedging_gain",
    "oth_income": "other_income",
    "asset_disp_income": "asset_disposal_income",
    "continued_net_profit": "continuing_operations_net_profit",
    "end_net_profit": "discontinued_operations_net_profit",
    "update_flag": "is_update",
}
TUSHARE_INCOME_FIELDS = list(TUSHARE_INCOME_FIELD_MAP.keys())
INCOME_COLUMNS = list(TUSHARE_INCOME_FIELD_MAP.values()) + ["update_time"]

# ---------------------------------------------------------------------------
# Balance sheet (balancesheet / balancesheet_vip)
# ---------------------------------------------------------------------------
TUSHARE_BALANCE_SHEET_FIELD_MAP = {
    **_STATEMENT_HEADER_MAP,
    "total_share": "total_shares",
    "cap_rese": "capital_reserve",
    "undistr_porfit": "undistributed_profit",
    "surplus_rese": "surplus_reserve",
    "special_rese": "special_reserve",
    "money_cap": "cash",
    "trad_asset": "trading_financial_assets",
    "notes_receiv": "notes_receivable",
    "accounts_receiv": "accounts_receivable",
    "oth_receiv": "other_receivables",
    "prepayment": "prepayments",
    "div_receiv": "dividends_receivable",
    "int_receiv": "interest_receivable",
    "inventories": "inventories",
    "amor_exp": "amortized_expenses",
    "nca_within_1y": "non_current_assets_due_within_1y",
    "sett_rsrv": "settlement_reserve",
    "loanto_oth_bank_fi": "loans_to_other_banks",
    "premium_receiv": "premiums_receivable",
    "reinsur_receiv": "reinsurance_receivable",
    "reinsur_res_receiv": "reinsurance_reserve_receivable",
    "pur_resale_fa": "financial_assets_purchased_for_resale",
    "oth_cur_assets": "other_current_assets",
    "total_cur_assets": "total_current_assets",
    "fa_avail_for_sale": "available_for_sale_financial_assets",
    "htm_invest": "held_to_maturity_investments",
    "lt_eqt_invest": "long_term_equity_investments",
    "invest_real_estate": "investment_property",
    "time_deposits": "time_deposits",
    "oth_assets": "other_assets",
    "lt_rec": "long_term_receivables",
    "fix_assets": "fixed_assets",
    "cip": "construction_in_progress",
    "const_materials": "construction_materials",
    "fixed_assets_disp": "fixed_assets_pending_disposal",
    "produc_bio_assets": "productive_biological_assets",
    "oil_and_gas_assets": "oil_and_gas_assets",
    "intan_assets": "intangible_assets",
    "r_and_d": "development_expenditure",
    "goodwill": "goodwill",
    "lt_amor_exp": "long_term_deferred_expenses",
    "defer_tax_assets": "deferred_tax_assets",
    "decr_in_disbur": "loans_and_advances",
    "oth_nca": "other_non_current_assets",
    "total_nca": "total_non_current_assets",
    "cash_reser_cb": "cash_reserves_at_central_bank",
    "depos_in_oth_bfi": "deposits_in_other_banks",
    "prec_metals": "precious_metals",
    "deriv_assets": "derivative_assets",
    "rr_reins_une_prem": "reinsurance_unearned_premium_reserve",
    "rr_reins_outstd_cla": "reinsurance_outstanding_claims_reserve",
    "rr_reins_lins_liab": "reinsurance_life_insurance_reserve",
    "rr_reins_lthins_liab": "reinsurance_long_term_health_reserve",
    "refund_depos": "refundable_deposits",
    "ph_pledge_loans": "policy_pledge_loans",
    "refund_cap_depos": "refundable_capital_deposits",
    "indep_acct_assets": "independent_account_assets",
    "client_depos": "client_deposits",
    "client_prov": "client_provisions",
    "transac_seat_fee": "exchange_seat_fees",
    "invest_as_receiv": "investments_receivable",
    "total_assets": "total_assets",
    "lt_borr": "long_term_borrowings",
    "st_borr": "short_term_borrowings",
    "cb_borr": "central_bank_borrowings",
    "depos_ib_deposits": "interbank_deposits",
    "loan_oth_bank": "loans_from_other_banks",
    "trading_fl": "trading_financial_liabilities",
    "notes_payable": "notes_payable",
    "acct_payable": "accounts_payable",
    "adv_receipts": "advances_from_customers",
    "sold_for_repur_fa": "financial_assets_sold_for_repurchase",
    "comm_payable": "commissions_payable",
    "payroll_payable": "payroll_payable",
    "taxes_payable": "taxes_payable",
    "int_payable": "interest_payable",
    "div_payable": "dividends_payable",
    "oth_payable": "other_payables",
    "acc_exp": "accrued_expenses",
    "deferred_inc": "deferred_income",
    "st_bonds_payable": "short_term_bonds_payable",
    "payable_to_reinsurer": "reinsurance_payable",
    "rsrv_insur_cont": "insurance_contract_reserve",
    "acting_trading_sec": "agency_securities_trading",
    "acting_uw_sec": "agency_securities_underwriting",
    "non_cur_liab_due_1y": "non_current_liabilities_due_within_1y",
    "oth_cur_liab": "other_current_liabilities",
    "total_cur_liab": "total_current_liabilities",
    "bond_payable": "bonds_payable",
    "lt_payable": "long_term_payables",
    "specific_payables": "special_payables",
    "estimated_liab": "provisions",
    "defer_tax_liab": "deferred_tax_liabilities",
    "defer_inc_non_cur_liab": "deferred_income_non_current",
    "oth_ncl": "other_non_current_liabilities",
    "total_ncl": "total_non_current_liabilities",
    "depos_oth_bfi": "deposits_from_other_banks",
    "deriv_liab": "derivative_liabilities",
    "depos": "customer_deposits",
    "agency_bus_liab": "agency_business_liabilities",
    "oth_liab": "other_liabilities",
    "prem_receiv_adva": "premiums_received_in_advance",
    "depos_received": "deposits_received",
    "ph_invest": "policyholder_investment_funds",
    "reser_une_prem": "unearned_premium_reserve",
    "reser_outstd_claims": "outstanding_claims_reserve",
    "reser_lins_liab": "life_insurance_reserve",
    "reser_lthins_liab": "long_term_health_insurance_reserve",
    "indept_acc_liab": "independent_account_liabilities",
    "pledge_borr": "pledged_borrowings",
    "indem_payable": "indemnities_payable",
    "policy_div_payable": "policy_dividends_payable",
    "total_liab": "total_liabilities",
    "treasury_share": "treasury_shares",
    "ordin_risk_reser": "general_risk_reserve",
    "forex_differ": "foreign_currency_translation_difference",
    "invest_loss_unconf": "unrecognized_investment_loss",
    "minority_int": "minority_interest",
    "total_hldr_eqy_exc_min_int": "equity_attributable_to_parent",
    "total_hldr_eqy_inc_min_int": "total_equity",
    "total_liab_hldr_eqy": "total_liabilities_and_equity",
    "lt_payroll_payable": "long_term_payroll_payable",
    "oth_comp_income": "other_comprehensive_income",
    "oth_eqt_tools": "other_equity_instruments",
    "oth_eqt_tools_p_shr": "preferred_shares",
    "lending_funds": "lending_funds",
    "acc_receivable": "receivables",
    "st_fin_payable": "short_term_financing_payable",
    "payables": "payables",
    "hfs_assets": "held_for_sale_assets",
    "hfs_sales": "held_for_sale_liabilities",
    "cost_fin_assets": "amortized_cost_financial_assets",
    "fair_value_fin_assets": "fair_value_financial_assets",
    "cip_total": "construction_in_progress_total",
    "oth_pay_total": "other_payables_total",
    "long_pay_total": "long_term_payables_total",
    "debt_invest": "debt_investments",
    "oth_debt_invest": "other_debt_investments",
    "oth_eq_invest": "other_equity_investments",
    "oth_illiq_fin_assets": "other_non_current_financial_assets",
    "oth_eq_ppbond": "other_equity_perpetual_bonds",
    "receiv_financing": "receivables_financing",
    "use_right_assets": "right_of_use_assets",
    "lease_liab": "lease_liabilities",
    "contract_assets": "contract_assets",
    "contract_liab": "contract_liabilities",
    "accounts_receiv_bill": "accounts_and_notes_receivable",
    "accounts_pay": "accounts_and_notes_payable",
    "oth_rcv_total": "other_receivables_total",
    "fix_assets_total": "fixed_assets_total",
    "update_flag": "is_update",
}
TUSHARE_BALANCE_SHEET_FIELDS = list(TUSHARE_BALANCE_SHEET_FIELD_MAP.keys())
BALANCE_SHEET_COLUMNS = list(TUSHARE_BALANCE_SHEET_FIELD_MAP.values()) + ["update_time"]

# ---------------------------------------------------------------------------
# Cash flow statement (cashflow / cashflow_vip)
# ---------------------------------------------------------------------------
TUSHARE_CASH_FLOW_FIELD_MAP = {
    **_STATEMENT_HEADER_MAP,
    "net_profit": "net_profit",
    "finan_exp": "financial_expense",
    "c_fr_sale_sg": "cash_from_sales",
    "recp_tax_rends": "tax_refunds_received",
    "n_depos_incr_fi": "net_increase_in_deposits",
    "n_incr_loans_cb": "net_increase_in_central_bank_loans",
    "n_inc_borr_oth_fi": "net_increase_in_interbank_borrowings",
    "prem_fr_orig_contr": "cash_from_original_insurance_premiums",
    "n_incr_insured_dep": "net_increase_in_insured_deposits",
    "n_reinsur_prem": "net_reinsurance_premiums",
    "n_incr_disp_tfa": "net_increase_from_trading_assets_disposal",
    "ifc_cash_incr": "interest_and_commission_cash_received",
    "n_incr_disp_faas": "net_increase_from_available_for_sale_disposal",
    "n_incr_loans_oth_bank": "net_increase_in_loans_from_other_banks",
    "n_cap_incr_repur": "net_increase_in_repurchase_capital",
    "c_fr_oth_operate_a": "other_operating_cash_received",
    "c_inf_fr_operate_a": "operating_cash_inflow",
    "c_paid_goods_s": "cash_paid_for_goods_and_services",
    "c_paid_to_for_empl": "cash_paid_to_employees",
    "c_paid_for_taxes": "cash_paid_for_taxes",
    "n_incr_clt_loan_adv": "net_increase_in_client_loans",
    "n_incr_dep_cbob": "net_increase_in_deposits_at_central_bank_and_banks",
    "c_pay_claims_orig_inco": "cash_paid_for_original_insurance_claims",
    "pay_handling_chrg": "handling_charges_paid",
    "pay_comm_insur_plcy": "policy_dividends_paid",
    "oth_cash_pay_oper_act": "other_operating_cash_paid",
    "st_cash_out_act": "operating_cash_outflow",
    "n_cashflow_act": "operating_cash_flow",
    "oth_recp_ral_inv_act": "other_investing_cash_received",
    "c_disp_withdrwl_invest": "cash_from_investment_disposal",
    "c_recp_return_invest": "cash_from_investment_returns",
    "n_recp_disp_fiolta": "cash_from_fixed_asset_disposal",
    "n_recp_disp_sobu": "cash_from_subsidiary_disposal",
    "stot_inflows_inv_act": "investing_cash_inflow",
    "c_pay_acq_const_fiolta": "cash_paid_for_fixed_assets",
    "c_paid_invest": "cash_paid_for_investments",
    "n_disp_subs_oth_biz": "cash_paid_for_subsidiary_acquisition",
    "oth_pay_ral_inv_act": "other_investing_cash_paid",
    "n_incr_pledge_loan": "net_increase_in_pledge_loans",
    "stot_out_inv_act": "investing_cash_outflow",
    "n_cashflow_inv_act": "investing_cash_flow",
    "c_recp_borrow": "cash_from_borrowings",
    "proc_issue_bonds": "cash_from_bond_issuance",
    "oth_cash_recp_ral_fnc_act": "other_financing_cash_received",
    "stot_cash_in_fnc_act": "financing_cash_inflow",
    "free_cashflow": "free_cash_flow",
    "c_prepay_amt_borr": "cash_paid_for_debt_repayment",
    "c_pay_dist_dpcp_int_exp": "cash_paid_for_dividends_and_interest",
    "incl_dvd_profit_paid_sc_ms": "dividends_paid_to_minority",
    "oth_cashpay_ral_fnc_act": "other_financing_cash_paid",
    "stot_cashout_fnc_act": "financing_cash_outflow",
    "n_cash_flows_fnc_act": "financing_cash_flow",
    "eff_fx_flu_cash": "fx_effect_on_cash",
    "n_incr_cash_cash_equ": "net_increase_in_cash",
    "c_cash_equ_beg_period": "cash_beginning_of_period",
    "c_cash_equ_end_period": "cash_end_of_period",
    "c_recp_cap_contrib": "cash_from_capital_contributions",
    "incl_cash_rec_saims": "cash_from_minority_contributions",
    "uncon_invest_loss": "unrecognized_investment_loss",
    "prov_depr_assets": "asset_impairment_provision",
    "depr_fa_coga_dpba": "depreciation_of_fixed_assets",
    "amort_intang_assets": "amortization_of_intangible_assets",
    "lt_amort_deferred_exp": "amortization_of_long_term_deferred_expenses",
    "decr_deferred_exp": "decrease_in_deferred_expenses",
    "incr_acc_exp": "increase_in_accrued_expenses",
    "loss_disp_fiolta": "loss_on_fixed_asset_disposal",
    "loss_scr_fa": "loss_on_fixed_asset_scrapping",
    "loss_fv_chg": "fair_value_change_loss",
    "invest_loss": "investment_loss",
    "decr_def_inc_tax_assets": "decrease_in_deferred_tax_assets",
    "incr_def_inc_tax_liab": "increase_in_deferred_tax_liabilities",
    "decr_inventories": "decrease_in_inventories",
    "decr_oper_payable": "decrease_in_operating_receivables",
    "incr_oper_payable": "increase_in_operating_payables",
    "others": "other_adjustments",
    "im_net_cashflow_oper_act": "indirect_operating_cash_flow",
    "conv_debt_into_cap": "debt_converted_to_equity",
    "conv_copbonds_due_within_1y": "convertible_bonds_due_within_1y",
    "fa_fnc_leases": "fixed_assets_under_finance_lease",
    "im_n_incr_cash_equ": "indirect_net_increase_in_cash",
    "net_dism_capital_add": "net_capital_added",
    "net_cash_rece_sec": "net_cash_from_securities",
    "credit_impa_loss": "credit_impairment_loss",
    "use_right_asset_dep": "right_of_use_asset_depreciation",
    "oth_loss_asset": "other_asset_loss",
    "end_bal_cash": "cash_ending_balance",
    "beg_bal_cash": "cash_beginning_balance",
    "end_bal_cash_equ": "cash_equivalents_ending_balance",
    "beg_bal_cash_equ": "cash_equivalents_beginning_balance",
    "update_flag": "is_update",
}
TUSHARE_CASH_FLOW_FIELDS = list(TUSHARE_CASH_FLOW_FIELD_MAP.keys())
CASH_FLOW_COLUMNS = list(TUSHARE_CASH_FLOW_FIELD_MAP.values()) + ["update_time"]

# ---------------------------------------------------------------------------
# Financial indicators (fina_indicator / fina_indicator_vip)
# ---------------------------------------------------------------------------
TUSHARE_FINANCIAL_INDICATOR_FIELD_MAP = {
    "ts_code": "code",
    "ann_date": "announce_date",
    "end_date": "report_period",
    "eps": "eps",
    "dt_eps": "diluted_eps",
    "total_revenue_ps": "total_revenue_per_share",
    "revenue_ps": "revenue_per_share",
    "capital_rese_ps": "capital_reserve_per_share",
    "surplus_rese_ps": "surplus_reserve_per_share",
    "undist_profit_ps": "undistributed_profit_per_share",
    "extra_item": "non_recurring_items",
    "profit_dedt": "net_profit_excluding_non_recurring",
    "gross_margin": "gross_margin",
    "current_ratio": "current_ratio",
    "quick_ratio": "quick_ratio",
    "cash_ratio": "cash_ratio",
    "invturn_days": "inventory_turnover_days",
    "arturn_days": "receivables_turnover_days",
    "inv_turn": "inventory_turnover",
    "ar_turn": "receivables_turnover",
    "ca_turn": "current_asset_turnover",
    "fa_turn": "fixed_asset_turnover",
    "assets_turn": "total_asset_turnover",
    "op_income": "operating_income",
    "valuechange_income": "value_change_income",
    "interst_income": "interest_income",
    "daa": "depreciation_and_amortization",
    "ebit": "ebit",
    "ebitda": "ebitda",
    "fcff": "fcff",
    "fcfe": "fcfe",
    "current_exint": "current_liabilities_excluding_interest_bearing",
    "noncurrent_exint": "non_current_liabilities_excluding_interest_bearing",
    "interestdebt": "interest_bearing_debt",
    "netdebt": "net_debt",
    "tangible_asset": "tangible_assets",
    "working_capital": "working_capital",
    "networking_capital": "net_working_capital",
    "invest_capital": "invested_capital",
    "retained_earnings": "retained_earnings",
    "diluted2_eps": "diluted_eps_2",
    "bps": "book_value_per_share",
    "ocfps": "operating_cash_flow_per_share",
    "retainedps": "retained_earnings_per_share",
    "cfps": "cash_flow_per_share",
    "ebit_ps": "ebit_per_share",
    "fcff_ps": "fcff_per_share",
    "fcfe_ps": "fcfe_per_share",
    "netprofit_margin": "net_profit_margin",
    "grossprofit_margin": "gross_profit_margin",
    "cogs_of_sales": "cost_of_sales_ratio",
    "expense_of_sales": "expense_of_sales_ratio",
    "profit_to_gr": "profit_to_revenue",
    "saleexp_to_gr": "selling_expense_to_revenue",
    "adminexp_of_gr": "administrative_expense_to_revenue",
    "finaexp_of_gr": "financial_expense_to_revenue",
    "impai_ttm": "impairment_to_revenue_ttm",
    "gc_of_gr": "operating_cost_to_revenue",
    "op_of_gr": "operating_profit_to_revenue",
    "ebit_of_gr": "ebit_to_revenue",
    "roe": "roe",
    "roe_waa": "roe_weighted",
    "roe_dt": "roe_excluding_non_recurring",
    "roa": "roa",
    "npta": "net_profit_to_total_assets",
    "roic": "roic",
    "roe_yearly": "roe_annualized",
    "roa2_yearly": "roa_annualized",
    "roe_avg": "roe_average",
    "opincome_of_ebt": "operating_income_to_pretax_profit",
    "investincome_of_ebt": "investment_income_to_pretax_profit",
    "n_op_profit_of_ebt": "non_operating_profit_to_pretax_profit",
    "tax_to_ebt": "tax_to_pretax_profit",
    "dtprofit_to_profit": "profit_excluding_non_recurring_to_profit",
    "salescash_to_or": "sales_cash_to_revenue",
    "ocf_to_or": "operating_cash_flow_to_revenue",
    "ocf_to_opincome": "operating_cash_flow_to_operating_income",
    "capitalized_to_da": "capitalized_to_depreciation",
    "debt_to_assets": "debt_to_assets",
    "assets_to_eqt": "assets_to_equity",
    "dp_assets_to_eqt": "assets_to_equity_dupont",
    "ca_to_assets": "current_assets_to_assets",
    "nca_to_assets": "non_current_assets_to_assets",
    "tbassets_to_totalassets": "tangible_assets_to_assets",
    "int_to_talcap": "interest_bearing_debt_to_capital",
    "eqt_to_talcapital": "equity_to_capital",
    "currentdebt_to_debt": "current_liabilities_to_liabilities",
    "longdeb_to_debt": "non_current_liabilities_to_liabilities",
    "ocf_to_shortdebt": "operating_cash_flow_to_current_liabilities",
    "debt_to_eqt": "debt_to_equity",
    "eqt_to_debt": "equity_to_debt",
    "eqt_to_interestdebt": "equity_to_interest_bearing_debt",
    "tangibleasset_to_debt": "tangible_assets_to_debt",
    "tangasset_to_intdebt": "tangible_assets_to_interest_bearing_debt",
    "tangibleasset_to_netdebt": "tangible_assets_to_net_debt",
    "ocf_to_debt": "operating_cash_flow_to_debt",
    "ocf_to_interestdebt": "operating_cash_flow_to_interest_bearing_debt",
    "ocf_to_netdebt": "operating_cash_flow_to_net_debt",
    "ebit_to_interest": "ebit_interest_coverage",
    "longdebt_to_workingcapital": "long_term_debt_to_working_capital",
    "ebitda_to_debt": "ebitda_to_debt",
    "turn_days": "operating_cycle_days",
    "roa_yearly": "roa_annualized_2",
    "roa_dp": "roa_dupont",
    "fixed_assets": "fixed_assets_total",
    "profit_prefin_exp": "profit_before_financial_expense",
    "non_op_profit": "non_operating_profit",
    "op_to_ebt": "operating_profit_to_pretax_profit",
    "nop_to_ebt": "non_operating_profit_to_pretax_profit_2",
    "ocf_to_profit": "operating_cash_flow_to_profit",
    "cash_to_liqdebt": "cash_to_current_liabilities",
    "cash_to_liqdebt_withinterest": "cash_to_interest_bearing_current_liabilities",
    "op_to_liqdebt": "operating_profit_to_current_liabilities",
    "op_to_debt": "operating_profit_to_liabilities",
    "roic_yearly": "roic_annualized",
    "total_fa_trun": "fixed_asset_turnover_total",
    "profit_to_op": "profit_to_operating_profit",
    "q_opincome": "quarter_operating_income",
    "q_investincome": "quarter_investment_income",
    "q_dtprofit": "quarter_profit_excluding_non_recurring",
    "q_eps": "quarter_eps",
    "q_netprofit_margin": "quarter_net_profit_margin",
    "q_gsprofit_margin": "quarter_gross_profit_margin",
    "q_exp_to_sales": "quarter_expense_to_sales",
    "q_profit_to_gr": "quarter_profit_to_revenue",
    "q_saleexp_to_gr": "quarter_selling_expense_to_revenue",
    "q_adminexp_to_gr": "quarter_administrative_expense_to_revenue",
    "q_finaexp_to_gr": "quarter_financial_expense_to_revenue",
    "q_impair_to_gr_ttm": "quarter_impairment_to_revenue_ttm",
    "q_gc_to_gr": "quarter_operating_cost_to_revenue",
    "q_op_to_gr": "quarter_operating_profit_to_revenue",
    "q_roe": "quarter_roe",
    "q_dt_roe": "quarter_roe_excluding_non_recurring",
    "q_npta": "quarter_net_profit_to_total_assets",
    "q_opincome_to_ebt": "quarter_operating_income_to_pretax_profit",
    "q_investincome_to_ebt": "quarter_investment_income_to_pretax_profit",
    "q_dtprofit_to_profit": "quarter_profit_excluding_non_recurring_to_profit",
    "q_salescash_to_or": "quarter_sales_cash_to_revenue",
    "q_ocf_to_sales": "quarter_operating_cash_flow_to_sales",
    "q_ocf_to_or": "quarter_operating_cash_flow_to_revenue",
    "basic_eps_yoy": "basic_eps_yoy",
    "dt_eps_yoy": "diluted_eps_yoy",
    "cfps_yoy": "cash_flow_per_share_yoy",
    "op_yoy": "operating_profit_yoy",
    "ebt_yoy": "pretax_profit_yoy",
    "netprofit_yoy": "net_profit_yoy",
    "dt_netprofit_yoy": "net_profit_excluding_non_recurring_yoy",
    "ocf_yoy": "operating_cash_flow_yoy",
    "roe_yoy": "roe_yoy",
    "bps_yoy": "book_value_per_share_yoy",
    "assets_yoy": "total_assets_yoy",
    "eqt_yoy": "equity_yoy",
    "tr_yoy": "total_revenue_yoy",
    "or_yoy": "revenue_yoy",
    "q_gr_yoy": "quarter_revenue_yoy",
    "q_gr_qoq": "quarter_revenue_qoq",
    "q_sales_yoy": "quarter_sales_yoy",
    "q_sales_qoq": "quarter_sales_qoq",
    "q_op_yoy": "quarter_operating_profit_yoy",
    "q_op_qoq": "quarter_operating_profit_qoq",
    "q_profit_yoy": "quarter_profit_yoy",
    "q_profit_qoq": "quarter_profit_qoq",
    "q_netprofit_yoy": "quarter_net_profit_yoy",
    "q_netprofit_qoq": "quarter_net_profit_qoq",
    "equity_yoy": "equity_attributable_yoy",
    "rd_exp": "research_and_development_expense",
    "update_flag": "is_update",
}
TUSHARE_FINANCIAL_INDICATOR_FIELDS = list(TUSHARE_FINANCIAL_INDICATOR_FIELD_MAP.keys())
FINANCIAL_INDICATOR_COLUMNS = list(TUSHARE_FINANCIAL_INDICATOR_FIELD_MAP.values()) + ["update_time"]
INDICATOR_KEY_COLUMNS = ["code", "report_period", "announce_date"]

# ---------------------------------------------------------------------------
# Earnings forecast (forecast / forecast_vip)
# ---------------------------------------------------------------------------
TUSHARE_FORECAST_FIELD_MAP = {
    "ts_code": "code",
    "ann_date": "announce_date",
    "end_date": "report_period",
    "type": "forecast_type",
    "p_change_min": "profit_change_min",
    "p_change_max": "profit_change_max",
    "net_profit_min": "net_profit_min",
    "net_profit_max": "net_profit_max",
    "last_parent_net": "last_year_net_profit",
    "first_ann_date": "first_announce_date",
    "summary": "summary",
    "change_reason": "change_reason",
}
TUSHARE_FORECAST_FIELDS = list(TUSHARE_FORECAST_FIELD_MAP.keys())
FORECAST_COLUMNS = list(TUSHARE_FORECAST_FIELD_MAP.values()) + ["update_time"]
FORECAST_KEY_COLUMNS = ["code", "report_period", "announce_date", "forecast_type"]

# ---------------------------------------------------------------------------
# Earnings express (express / express_vip)
# ---------------------------------------------------------------------------
TUSHARE_EXPRESS_FIELD_MAP = {
    "ts_code": "code",
    "ann_date": "announce_date",
    "end_date": "report_period",
    "revenue": "revenue",
    "operate_profit": "operating_profit",
    "total_profit": "total_profit",
    "n_income": "net_profit",
    "total_assets": "total_assets",
    "total_hldr_eqy_exc_min_int": "equity_attributable_to_parent",
    "diluted_eps": "diluted_eps",
    "diluted_roe": "diluted_roe",
    "yoy_net_profit": "net_profit_yoy",
    "bps": "book_value_per_share",
    "yoy_sales": "revenue_yoy",
    "yoy_op": "operating_profit_yoy",
    "yoy_tp": "total_profit_yoy",
    "yoy_dedu_np": "net_profit_excluding_non_recurring_yoy",
    "yoy_eps": "eps_yoy",
    "yoy_roe": "roe_yoy",
    "growth_assets": "total_assets_growth",
    "yoy_equity": "equity_yoy",
    "growth_bps": "book_value_per_share_growth",
    "or_last_year": "revenue_last_year",
    "op_last_year": "operating_profit_last_year",
    "tp_last_year": "total_profit_last_year",
    "np_last_year": "net_profit_last_year",
    "eps_last_year": "eps_last_year",
    "open_net_assets": "net_assets_beginning",
    "open_bps": "book_value_per_share_beginning",
    "perf_summary": "performance_summary",
    "is_audit": "is_audited",
    "remark": "remark",
}
TUSHARE_EXPRESS_FIELDS = list(TUSHARE_EXPRESS_FIELD_MAP.keys())
EXPRESS_COLUMNS = list(TUSHARE_EXPRESS_FIELD_MAP.values()) + ["update_time"]
EXPRESS_KEY_COLUMNS = ["code", "report_period", "announce_date"]

# ---------------------------------------------------------------------------
# Dividends (dividend), fetched per stock
# ---------------------------------------------------------------------------
TUSHARE_DIVIDEND_FIELD_MAP = {
    "ts_code": "code",
    "end_date": "report_period",
    "ann_date": "announce_date",
    "div_proc": "process",
    "stk_div": "stock_dividend_ratio",
    "stk_bo_rate": "bonus_share_ratio",
    "stk_co_rate": "capitalization_ratio",
    "cash_div": "cash_dividend_after_tax",
    "cash_div_tax": "cash_dividend_before_tax",
    "record_date": "record_date",
    "ex_date": "ex_dividend_date",
    "pay_date": "pay_date",
    "div_listdate": "share_listing_date",
    "imp_ann_date": "implementation_announce_date",
    "base_date": "base_date",
    "base_share": "base_shares",
}
TUSHARE_DIVIDEND_FIELDS = list(TUSHARE_DIVIDEND_FIELD_MAP.keys())
DIVIDEND_COLUMNS = list(TUSHARE_DIVIDEND_FIELD_MAP.values()) + ["update_time"]
# Tushare base_share is in 万股.
TUSHARE_DIVIDEND_SHARE_TO_LOCAL = 10000
DIVIDEND_PAGE_SIZE = 50

# ---------------------------------------------------------------------------
# Disclosure schedule (disclosure_date), fetched per report period
# ---------------------------------------------------------------------------
TUSHARE_DISCLOSURE_DATE_FIELD_MAP = {
    "ts_code": "code",
    "ann_date": "announce_date",
    "end_date": "report_period",
    "pre_date": "planned_date",
    "actual_date": "actual_date",
    "modify_date": "modified_dates",
}
TUSHARE_DISCLOSURE_DATE_FIELDS = list(TUSHARE_DISCLOSURE_DATE_FIELD_MAP.keys())
DISCLOSURE_DATE_COLUMNS = list(TUSHARE_DISCLOSURE_DATE_FIELD_MAP.values()) + ["update_time"]
DISCLOSURE_DATE_START_DATE = "20000101"

# Bulk (vip) endpoints return one period for every company per request.
TUSHARE_BULK_STATEMENT_APIS = {
    "income": "income_vip",
    "balance_sheet": "balancesheet_vip",
    "cash_flow": "cashflow_vip",
    "indicator": "fina_indicator_vip",
    "forecast": "forecast_vip",
    "express": "express_vip",
}
